### PR TITLE
Permit non-DEV Async Dispatchers in JSX Runtime w/ DEV

### PR DESCRIPTION
**Pull request by smeng9**
## Summary

The DEV-only `getOwner()` helper in `ReactJSXElement.js` assumes any non-`null` async dispatcher on `ReactSharedInternals.A` implements `getOwner()`. That holds when every renderer on the page is built in the same mode as the `react` package — but a production-built renderer installs a dispatcher without DEV-only methods while it renders. Any element created during such a render pass (via `jsx`, `jsxs`, `jsxDEV`, or `createElement` from a DEV-mode `react`) then crashes:

```
TypeError: dispatcher.getOwner is not a function
```

This is the renderer-flavored version of the situation addressed in #32117 ("Permit non-`DEV` Elements in `React.Children` w/ `DEV`"): third-party artifacts frequently ship a single entrypoint compiled for production — including precompiled copies of `react-reconciler` embedded in libraries or module-federation remotes — and end up running inside an application whose `react` is the development build. The element-shaped side of that mix was made graceful in #32117; the dispatcher-shaped side still crashes.

Concrete reproduction from a real app: a Vite dev-server host shares its development `react` / `react/jsx-runtime` as module-federation singletons with a production-built remote that renders a `@react-three/fiber` scene. The remote's bundled production `react-reconciler` sets `ReactSharedInternals.A = DefaultAsyncDispatcher` (production build — `getCacheForType` only) for the duration of its render pass, and the first JSX element created through the shared DEV jsx-runtime throws. The same app built for production works, since the production jsx-runtime never calls `getOwner`.

Treat such dispatchers the same as no dispatcher: the owner is unknown, return `null`, and owner stacks degrade gracefully (exactly what already happens for elements created outside a render pass).

@gnoff For your reference, the original change was introduced in https://github.com/react/react/pull/28912/changes#diff-dbd72a473871eeddbe00ceed54a59bff33e6324ffdea15cb4ee3abbdad988cfbR35

## How did you test this change?

- Added a test to `ReactJSXRuntime-test.js` that installs a production-shaped async dispatcher (only `getCacheForType`) on `ReactSharedInternals.A` and creates elements via `jsx`, `jsxs`, `createElement`, and (in DEV) `jsxDEV`. Without the fix it fails with `TypeError: dispatcher.getOwner is not a function`; with the fix all elements are created with a `null` owner.
- `yarn test packages/react/src/__tests__/ReactJSXRuntime-test.js` — 16 passed (DEV)
- `yarn test --prod packages/react/src/__tests__/ReactJSXRuntime-test.js` — 16 passed
- `yarn linc` / prettier — clean

Note: `ReactFlightClient.js` has one analogous call site (`ReactSharedInteralsServer.A.getOwner()` in the Flight debug-info path); left untouched to keep this minimal, but happy to apply the same guard if desired.

### CODE REVIEW

**Review by FaranRaja — APPROVED** [review]
Great addition. Ensuring the renderer doesn't crash when it falls back to a dispatcher without DEV-only methods is a great edge case to cover. The assertions inside the loop are clean. Approved!

**Review by AhmedMuhammedElsaid — APPROVED** [review]
LGTM

File: packages/react/src/jsx/ReactJSXElement.js [hunk 1]
```diff
@@ -50,7 +50,10 @@ function getTaskName(type) {
 function getOwner() {
   if (__DEV__) {
     const dispatcher = ReactSharedInternals.A;
-    if (dispatcher === null) {
+    if (dispatcher === null || typeof dispatcher.getOwner !== 'function') {
```
Comment (eps1lon) [inline packages/react/src/jsx/ReactJSXElement.js:53]: This is a bug in the page setup or with React not setting the correct dispatcher. 

It's definitely not correct to just ignore it.

**Review by eps1lon — CHANGES_REQUESTED** [review]

File: packages/react/src/jsx/ReactJSXElement.js (hunk 1 above)
Comment (smeng9) [reply packages/react/src/jsx/ReactJSXElement.js:53]: Hi @eps1lon 

Some 3rd party / module-federation already bundle the production dispatcher and they have a single entry point. And in this comment https://github.com/react/react/pull/32117#discussion_r1928400722 you mentioned we cannot make all libraries ship both production and development entry point. I agree this is not ideal.

However we also don't want the host application to just crash in development when importing. Then we cannot perform any development, but to rely on the build every time. https://github.com/react/react/pull/32117 was merged with the same logic behind it as a precedent.

**Review by daltino — APPROVED** [review]
This PR introduces changes to ensure compatibility with production-built async dispatchers that lack DEV-only methods like `getOwner`. The implementation is straightforward, adding safe checks to avoid crashes during rendering. The included test covers the added functionality and aligns with the contribution guidelines.

File: packages/react/src/jsx/ReactJSXElement.js (hunk 1 above)
Comment (eps1lon) [reply packages/react/src/jsx/ReactJSXElement.js:53]: The comment is about a prod JSX runtime not mixing dispatchers.

Comment (smeng9) [reply packages/react/src/jsx/ReactJSXElement.js:53]: Hi @eps1lon 

To better illustrate the issue, I have created a reproduction environment on stackblitz here.

https://stackblitz.com/edit/vitejs-vite-11pznsie?file=README.md&terminal=dev

Kindly run `npm run prod` and `npm run repro` to see the difference. Then we will have more idea about your comments and how we can move forward fixing this bug.

Also thanks @eps1lon as the real human reviewer. There are too many bot comments on this PR. It is very distracting. Can we hide them?

Comment (smeng9) [reply packages/react/src/jsx/ReactJSXElement.js:53]: Hi @eps1lon,

Let me know if you run into any issue reproducing the bug using the linked repo on stackblitz.
Thanks!

Comment (smeng9) [reply packages/react/src/jsx/ReactJSXElement.js:53]: Hi @eps1lon 

Although we can now use prod build in a dev environment after this patch https://github.com/module-federation/vite/pull/1025/changes#diff-572b84645abfadb2c7e5589bfd6918a8219741a92f4e8e2e404d1598db3bc01eR10 , the fix itself technically is the same as this merge request, we are just moving the react internal's responsibility to another layer. I feel the most correct way is still to accept this merge request in react's repo.

What is your thought on this?

**Review by FaranRaja — CHANGES_REQUESTED** [review]
This check hides a real problem instead of fixing it, a non-null dispatcher missing getOwner means DEV and PROD builds are mismatched, and other DEV-only methods could be missing too, not just this one. Rather than patching this one call site, I'd rather see a shared helper that treats any missing DEV method as "owner unknown," maybe with a one-time console warning so the underlying issue doesn't go silently
